### ISSUE TITLE
이름이 이상해요

### ISSUE THREAD

**Issue by tmddn3070** [SUTP-Project/COVID19_AutoSelfCheckDiscordBot#1]
disoonmicord-AutoSelfCheckDiosordBot으로 바꿔줘요
빼애애애애애애애애애애앵ㄱ

**Comment by tjwhang** [comment]
해당 기능은 저의 관리 팀이 검토하고 있습니다. 
저희가 학생인지라 개발을 학업과 병행하고 있어 시간이 좀 걸릴 수 있다는 점 양해 부탁드립니다. 
감사합니다.

**Comment by tmddn3070** [comment]
무무순미?
